# Generated by Django 5.2 on 2026-08-03 11:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='标题')),
                ('image', models.ImageField(upload_to='hero/bg/', verbose_name='图片')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='当前启用')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': 'Hero 背景图',
                'verbose_name_plural': 'Hero 背景图',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Journal · 站名', help_text='Hero 顶部小字,可用 "Journal · 站名" 占位。', max_length=120, verbose_name='眉标文字')),
                ('hero_title', models.CharField(default='文字,是思想的栖息地。', help_text='Hero 大标题。如需高亮某个词,请在"高亮词"字段填写该词(须与本字段中出现的词一致)。', max_length=200, verbose_name='主标题')),
                ('hero_accent_word', models.CharField(blank=True, default='思想', help_text='标题中要高亮(强调色 + 斜体)的词;留空则不高亮。该词必须在主标题中出现。', max_length=60, verbose_name='高亮词')),
                ('hero_subtitle', models.TextField(blank=True, default='记录代码、思考与生活的个人空间。', verbose_name='副标题')),
                ('hero_animation_choice', models.CharField(choices=[('char_rise', '逐字上升(默认)'), ('fade_up', '整块淡入上移'), ('typewriter', '打字机'), ('glitch', '故障抖动'), ('slide_reveal', '滑入遮罩揭示')], default='char_rise', max_length=20, verbose_name='入场动画')),
                ('hero_bg_type', models.CharField(choices=[('none', '无背景(纯色)'), ('blob', '光晕 blob(默认)'), ('image', '静态图片'), ('video', '动态视频')], default='blob', max_length=10, verbose_name='背景类型')),
                ('hero_bg_video', models.FileField(blank=True, help_text='背景类型选"动态视频"时使用。建议 mp4/webm,体积 < 5MB。', null=True, upload_to='hero/bg/', verbose_name='背景视频')),
                ('hero_bg_overlay', models.FloatField(default=0.35, help_text='0~1 之间的数值,用于压暗背景图/视频以突出文字。0=无遮罩,1=全黑。', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='背景遮罩透明度')),
                ('hero_cta_text', models.CharField(default='开始阅读', max_length=40, verbose_name='主按钮文字')),
                ('hero_cta_link', models.CharField(default='#posts', help_text='主按钮跳转地址。可用 #posts 锚点,或 /archive/ 等绝对路径。', max_length=200, verbose_name='主按钮链接')),
                ('hero_bg_image', models.ForeignKey(blank=True, help_text='背景类型选"静态图片"时使用。也可在 BackgroundImage 列表里点"设为当前"。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_configs', to='blog.backgroundimage', verbose_name='背景图片')),
            ],
            options={
                'verbose_name': '站点 Hero 配置',
                'verbose_name_plural': '站点 Hero 配置',
            },
        ),
    ]
