# Generated by Django 5.2 on 2026-08-03 14:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_slug_alter_post_slug_alter_tag_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order_in_collection',
            field=models.PositiveSmallIntegerField(blank=True, help_text='不填则按发布时间自动排;手动填 1、2、3……可自由指定顺序。', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='在合集中的序号'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='合集名')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True, verbose_name='URL 别名')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='简介')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='合集封面')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='已发布')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '合集',
                'verbose_name_plural': '合集',
                'ordering': ['-modified_time'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.collection', verbose_name='所属合集'),
        ),
    ]
