# Generated by Django 5.2 on 2026-08-03 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_text_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='首页 Hero 文字整体缩放百分比:100=原始大小,80=缩小,130=放大。', validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(150)], verbose_name='首页文字缩放'),
        ),
    ]
