# Generated by Django 5.2 on 2026-08-03 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_siteconfig_hero_text_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_text_scale',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_accent_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='标题高亮词大小百分比(相对主标题):100=与标题同大,120=放大。', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='高亮词缩放'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_eyebrow_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='眉标文字大小百分比:100=默认,80=缩小,150=放大。', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='眉标文字缩放'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subtitle_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='副标题大小百分比:100=默认,80=缩小,150=放大。', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='副标题缩放'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_title_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='主标题大小百分比:100=默认,80=缩小,150=放大。', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='主标题缩放'),
        ),
    ]
