# Generated by Django 6.0.7 on 2026-08-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_siteconfig_hero_text_scale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_accent_scale',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_eyebrow_scale',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_subtitle_scale',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_title_scale',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='card_big_fs',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='功能卡片大数字(时钟时间/天气温度/统计数字)的字号,单位 px。默认 40,留空用默认。', null=True, verbose_name='卡片大数字字号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='card_text_fs',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='功能卡片正文(导航/天气描述/热门标题/金句等)的字号,单位 px。默认 15,留空用默认。', null=True, verbose_name='卡片正文字号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_eyebrow_fs',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Hero 顶部小字(如 "Journal · 站名")的字号,单位 px。默认 18,留空用默认。', null=True, verbose_name='Hero 眉标字号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_meta_fs',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Hero 底部信息条(文章数/滚屏提示)的字号,单位 px。默认 12,留空用默认。', null=True, verbose_name='Hero 底部信息字号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subtitle_fs',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Hero 副标题的字号,单位 px。默认 18,留空用默认。', null=True, verbose_name='Hero 副标题字号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_title_fs',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Hero 大标题的字号,单位 px。默认 56,留空用默认。', null=True, verbose_name='Hero 主标题字号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='post_excerpt_fs',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='首页文章列表摘要的字号,单位 px。默认 15,留空用默认。', null=True, verbose_name='文章摘要字号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='post_meta_fs',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='首页文章列表元信息(日期/分类等)的字号,单位 px。默认 12,留空用默认。', null=True, verbose_name='文章元信息字号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='post_title_fs',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='首页文章列表标题的字号,单位 px。默认 23,留空用默认。', null=True, verbose_name='文章标题字号'),
        ),
    ]
