# Generated by Django 6.0.7 on 2026-08-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_siteconfig_hero_accent_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_markdown',
            field=models.TextField(blank=True, default='', help_text='前台 /about/ 页面正文,支持 Markdown。留空则显示模板内置的默认关于内容。', verbose_name='关于页内容(Markdown)'),
        ),
    ]
