# Generated by Django 6.0.7 on 2026-08-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_siteconfig_about_markdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=80, unique=True, verbose_name='URL 别名')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
            ],
            options={
                'verbose_name': '项目分类',
                'verbose_name_plural': '项目分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='项目名称')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='URL 别名')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='简介')),
                ('url', models.URLField(help_text='「查看项目」跳转地址,支持 https:// 外链或 /xxx/ 站内路径。', max_length=300, verbose_name='项目链接')),
                ('cover', models.ImageField(blank=True, help_text='可选,建议正方形,展示在项目卡片上。', null=True, upload_to='projects/', verbose_name='封面/图标')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='已发布')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='blog.projectcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['sort_order', '-created_time'],
            },
        ),
    ]
