# Generated by Django 6.0.7 on 2026-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_projectcategory_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='header_color',
            field=models.CharField(blank=True, default='', help_text='仅「手动」模式生效。格式 #RRGGBB,建议取壁纸中的一个主色调。', max_length=7, verbose_name='顶栏背景色'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='header_color_mode',
            field=models.CharField(choices=[('auto', '自动(从壁纸取色)'), ('manual', '手动指定颜色')], default='auto', help_text='自动: 从当前壁纸提取主色,自动选深/浅文字保证对比。手动: 用下方指定颜色作顶栏背景色。', max_length=10, verbose_name='顶栏配色模式'),
        ),
    ]
