# Generated by Django 6.0.7 on 2026-08-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_siteconfig_header_color_siteconfig_header_color_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='header_text_color',
            field=models.CharField(blank=True, default='', help_text='仅「手动」模式生效,可选。格式 #RRGGBB。留空则按背景色自动选深/浅文字。', max_length=7, verbose_name='顶栏文字颜色'),
        ),
    ]
