# Generated by Django 6.0.7 on 2026-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_siteconfig_header_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='cursor_style',
            field=models.CharField(choices=[('classic', '经典准心 + 圆环'), ('dog_bone', '🐶 狗狗 + 🦴 骨头'), ('chick_egg', '🐤 小鸡 + 🥚 蛋'), ('butterfly_star', '🦋 蝴蝶 + ✨ 星光'), ('cat_paw', '🐱 猫咪 + 🐾 爪印'), ('pen_quill', '✒️ 钢笔 + 💫 星芒')], default='classic', help_text='表情光标即时跟随鼠标,小跟班弹性跟在身后(停下时两表情连线方向与移动方向一致)。', max_length=20, verbose_name='光标样式'),
        ),
    ]
