# Generated by Django 6.0.7 on 2026-08-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_siteconfig_cursor_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='cursor_style',
            field=models.CharField(choices=[('classic', '经典准心'), ('pen', '✒️ 钢笔')], default='pen', help_text='自定义桌面光标,即时跟随鼠标,无跟随物。', max_length=20, verbose_name='光标样式'),
        ),
    ]
