# Generated by Django 6.0.7 on 2026-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_siteconfig_cursor_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='cursor_style',
            field=models.CharField(choices=[('classic', '经典准心'), ('pen', '✒️ 钢笔')], default='classic', help_text='白色准心即时跟随鼠标,accent 圆环弹性跟随其后;钢笔为可选替代准心。', max_length=20, verbose_name='光标样式'),
        ),
    ]
