# Generated by Django 6.0.7 on 2026-08-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_siteconfig_cursor_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='cursor_style',
        ),
    ]
