# Generated by Django 6.0.7 on 2026-08-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_siteconfig_cursor_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='post_style',
            field=models.CharField(choices=[('default', '默认(站点编辑风格)'), ('github', 'GitHub README 风格')], default='default', help_text='文章详情页正文的默认阅读风格。访客仍可在文章页顶部手动切换并记忆到本地。', max_length=10, verbose_name='文章阅读风格'),
        ),
    ]
